// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createWallet = `-- name: CreateWallet :exec
INSERT INTO wallets (user_id) VALUES ($1)
`

func (q *Queries) CreateWallet(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, createWallet, userID)
	return err
}
