basePath: /
definitions:
  internal_handlers.PaymentRequest:
    properties:
      amount:
        type: number
      user_id:
        type: integer
    required:
    - amount
    - user_id
    type: object
  response.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  response.SuccessResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: Микросервис оплаты.
  title: Payment Service API
  version: "1.0"
paths:
  /pay:
    post:
      consumes:
      - application/json
      description: Регистрирует платёж и отправляет его на обработку
      parameters:
      - description: Данные платежа
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.PaymentRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Оплатить со счёта пользователя
      tags:
      - payment
swagger: "2.0"
