// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PaymentStatusType string

const (
	PaymentStatusTypePending PaymentStatusType = "pending"
	PaymentStatusTypeSuccess PaymentStatusType = "success"
	PaymentStatusTypeFailure PaymentStatusType = "failure"
)

func (e *PaymentStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatusType(s)
	case string:
		*e = PaymentStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatusType: %T", src)
	}
	return nil
}

type NullPaymentStatusType struct {
	PaymentStatusType PaymentStatusType
	Valid             bool // Valid is true if PaymentStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatusType), nil
}

type Payment struct {
	ID        uuid.UUID
	UserID    int32
	Amount    pgtype.Numeric
	Status    PaymentStatusType
	CreatedAt pgtype.Timestamp
}
